app/src/main/res/layout/activity_main.xml, app/src/main/res/values/themes.xml
As per the requirements, we implemented the new header layout and replaced the default one
=> P2022-136 New header layout

app/src/main/AndroidManifest.xml, app/src/main/java/com/intive/patronage22/intivi/LoginActivity.kt, app/src/main/res/layout/activity_login.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/strings.xml
Creates LoginActivity with a header which appears on app launch.
=> P2022 698/create login activity

app/src/main/res/layout/activity_login.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/strings.xml
Adds two EditText fields - login and password with description. 
Adds one log in button. The button only exists.
=> P2022-701 Login Form

app/src/main/res/layout/activity_main.xml, app/src/main/res/layout/activity_main_screen.xml, app/src/main/res/layout/item_grid_home.xml, app/src/main/res/values/strings.xml
add item_grid_home.xml
add to this xml FrameLayout with single Text
include this layout in activity_main.xml in  outer layout section
=> P2022-707 Create Grid ITEM with movie on HomeScreen

app/src/main/java/com/intive/patronage22/intivi/Fragments/SignInFragment.kt, app/src/main/java/com/intive/patronage22/intivi/Fragments/SignUpFragment.kt, app/src/main/res/layout/fragment_sign_in.xml, app/src/main/res/layout/fragment_sign_up.xml, app/src/main/res/values/strings.xml
Add RelativeLayout with 3 EditText and a Button.
Navigate from SingUpFragment to MainActivity by click singUp button.
=> P2022 1320 register screen/create layout

app/src/main/java/com/intive/patronage22/intivi/Fragments/SignUpFragment.kt, app/src/main/res/drawable/bottom_button_background.xml, app/src/main/res/layout/fragment_sign_in.xml, app/src/main/res/layout/fragment_sign_up.xml, app/src/main/res/values/styles.xml
- removes 1 drawable file
- replaces AppCompatButton with Button
- changes logInUpButton style
=> Fix changes after merge

app/src/main/java/com/intive/patronage22/intivi/Fragments/SignInFragment.kt
- RFC Standard
- local part of email address: 64 chars limit
- domain part: 255 chars limit
=> P2022-1507 Login validation

app/src/main/java/com/intive/patronage22/intivi/Fragments/SignUpFragment.kt
- RFC Standard
- local part of email address: 64 chars limit
- domain part: 255 chars limit
=> P2022-1321 Register validation

app/src/main/java/com/intive/patronage22/intivi/Adapter/MainFragmentsAdapter.kt, app/src/main/java/com/intive/patronage22/intivi/Fragments/FavouritesFragment.kt, app/src/main/java/com/intive/patronage22/intivi/Fragments/GenresFragment.kt, app/src/main/java/com/intive/patronage22/intivi/Fragments/HomeFragment.kt, app/src/main/java/com/intive/patronage22/intivi/MainActivity.kt, app/src/main/res/layout/activity_main.xml, app/src/main/res/layout/fragment_favourites.xml, app/src/main/res/layout/fragment_genres.xml, app/src/main/res/layout/fragment_home.xml
Adds 3 fragments to MainActivity and navigation between them using tablayout.
Moves temporary navigation to Details Activity to Home fragment.
=> P2022-1327/MainActivity fragment navigation.

app/src/main/res/drawable/button_background.xml, app/src/main/res/drawable/ic_chevronright.xml, app/src/main/res/layout-land/activity_reset_password.xml, app/src/main/res/layout/activity_details.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/styles.xml
=> P2022-176 Adapts Details Screen to a large font size

app/src/main/java/com/intive/patronage22/intivi/Adapter/FragmentsAdapter.kt, app/src/main/java/com/intive/patronage22/intivi/Fragments/SignInFragment.kt, app/src/main/java/com/intive/patronage22/intivi/Fragments/SignUpFragment.kt, app/src/main/java/com/intive/patronage22/intivi/LoginActivity.kt, app/src/main/res/layout-land/activity_login.xml, app/src/main/res/layout/activity_login.xml, app/src/main/res/values/strings.xml
P2022-1319 Refresh layout to new designs
Changes ViewPager on ViewPager2
EditText cleaned when you return to the site.
=> P2022-1320 Create layout

app/build.gradle, app/src/androidTest/java/com/intive/patronage22/intivi/DatabaseValidatorTest.kt, app/src/main/java/com/intive/patronage22/intivi/DatabaseValidator.kt, app/src/main/java/com/intive/patronage22/intivi/database/DAO.kt
The test completes successfully, but is it done correctly?
=> P2022-1708/ Database unit test

app/src/main/AndroidManifest.xml, app/src/main/res/layout/activity_video_player.xml
Adjusts to turn by 180 degrees
Changes the details of setting items
=> P2022-1560 VideoPlayerScreen

app/src/main/java/com/intive/patronage22/intivi/VideoPlayerActivity.kt, app/src/main/res/values/styles.xml, app/src/main/res/values/themes.xml
Fixed icon color changes when switching to dark mode
=> P2022-1861 VideoPlayerScreen/Implement layout - bug

app/build.gradle, app/src/androidTest/java/com/intive/patronage22/intivi/DatabaseValidatorTest.kt, app/src/main/java/com/intive/patronage22/intivi/database/DAO.kt, app/src/main/java/com/intive/patronage22/intivi/database/User.kt, app/src/main/java/com/intive/patronage22/intivi/database/UserRepository.kt, app/src/main/java/com/intive/patronage22/intivi/database/UsersDatabase.kt
Cleans up database.
Integrates database with coroutines.
Fixes database unit test.
Orders gradle dependencies.
Example use:
```
val userRepo = UserRepository()
val usersList = arrayOf(User(0, "Alejandro", "sezam", "gabe.newel@steam.com"), User(0, "Michaelo", "abrakazam", "elon.musk@rocket.com"))
userRepo.initialize(applicationContext)
userRepo.insertVarargUser(lifecycleScope, *usersList)
lifecycleScope.launch{
userRepo.insertVarargUser(User(0,"Pedro", "alakazam", "bill.gates@microsoft.com"))
userRepo.insertVarargUser(*usersList)
}
```
Help wanted: Does runBlocking{} negate the purpose of coroutines? If so, how to extract a return value out of async when await() is a suspend function and itself must run inside of another coroutine or suspend function?
=> P2022-1323/clean up user database

app/src/main/res/layout/item_grid_home.xml
=> P2022-2070/Center grid item

app/src/main/java/com/intive/patronage22/intivi/Adapter/MovieListAdapter.kt, app/src/main/java/com/intive/patronage22/intivi/Adapter/RecyclerAdapter.kt, app/src/main/java/com/intive/patronage22/intivi/Fragments/HomeFragment.kt, app/src/main/java/com/intive/patronage22/intivi/ViewModels/HomeViewModel.kt, app/src/main/java/com/intive/patronage22/intivi/model/MovieItem.kt
Create data class for movie item
create movie list
add bind to home fragment
=> P2022-2071 Separete GridData

app/src/main/java/com/intive/patronage22/intivi/Fragments/SignUpFragment.kt, app/src/main/java/com/intive/patronage22/intivi/ViewModels/LoginViewModel.kt, app/src/main/java/com/intive/patronage22/intivi/database/UserRepository.kt, app/src/main/java/com/intive/patronage22/intivi/database/UsersDatabase.kt
Registers the user to local Room database.
=> P2022-1838/Register database integration

app/src/main/res/layout/activity_main.xml
Increased bottom tablayout height to accommodate large system font size.
=> P2022-2117/Font size bug

app/build.gradle, app/definitions.gradle
Creates definitions.gradle and moves definitions from build.gradle.
=> P2022-1817/Gradle def to ext

app/src/main/java/com/intive/patronage22/intivi/adapter/FavouritesListAdapter.kt, app/src/main/java/com/intive/patronage22/intivi/api/ApiService.kt, app/src/main/java/com/intive/patronage22/intivi/api/Constants.kt, app/src/main/java/com/intive/patronage22/intivi/fragment/FavouritesFragment.kt, app/src/main/java/com/intive/patronage22/intivi/fragment/HomeFragment.kt, app/src/main/java/com/intive/patronage22/intivi/model/FavouriteMovie.kt, app/src/main/java/com/intive/patronage22/intivi/model/Movie.kt, app/src/main/java/com/intive/patronage22/intivi/viewmodel/HomeViewModel.kt, app/src/main/java/com/intive/patronage22/intivi/viewmodel/LoginViewModel.kt, app/src/main/res/drawable/checkbox_favourites.xml, app/src/main/res/drawable/ic_favourite_grid_item.xml, app/src/main/res/drawable/ic_favourite_grid_item_fill.xml, app/src/main/res/layout/fragment_favourites.xml, app/src/main/res/layout/item_grid_home.xml, app/src/main/res/values/strings.xml
Integrates favourites with API.
Populates favourites fragment with favourited movies.
TODO: Update individual data items instead of whole set. Fix empty spaces appearing in recycler views.
=> P2022-XXX3 favourites api integration
